const numberButtons = document.querySelectorAll('[data-number]')
const operationButtons = document.querySelectorAll('[data-operator]')
const equalsButton = document.querySelectorAll('[data-equals]')
const deleteButton = document.querySelectorAll('[data-delete]')
const previousOperand = document.querySelectorAll('[data-previous-operand]')
const currentOperand = document.querySelectorAll('[data-current-operand]')